CREATE TABLE STUDENT (
    STUDENT_ID INT AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE BOOK (
    BOOK_ID INT AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(255),
    STUDENT_ID INT,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);